/*
 * Copyright (c) 2014-2026 Bjoern Kimminich & the OWASP Juice Shop contributors.
 * SPDX-License-Identifier: MIT
 */

import config from 'config'
import { type Request, type Response } from 'express'
import { BasketModel } from '../models/basket'
import { UserModel } from '../models/user'
import * as challengeUtils from '../lib/challengeUtils'
import * as utils from '../lib/utils'
import { challenges } from '../data/datacache'
import { generateSecret, verifySync } from 'otplib'
import * as security from '../lib/insecurity'

/**
 * Resolves the user acting on a 2FA endpoint from the persisted `Users` row.
 *
 * The session token signature is verified explicitly and only the user id of
 * the established server-side session is used to look the account up. Neither
 * the acting identity nor any credential material is taken from the (client
 * supplied) token claims, so forged or tampered tokens cannot select a foreign
 * account or provide the password reference value used for re-authentication.
 */
async function currentUserFromDatabase (req: Request) {
  const token = utils.jwtFrom(req)
  if (!token || !security.verify(token)) {
    throw new Error('You need to be logged in to manage 2FA')
  }

  const session = security.authenticatedUsers.get(token)
  const userId = session?.data?.id
  if (userId == null) {
    throw new Error('You need to be logged in to manage 2FA')
  }

  const user = await UserModel.findByPk(userId)
  if (user == null) {
    throw new Error('No such user found!')
  }
  return user
}

export async function verify (req: Request, res: Response) {
  const { tmpToken, totpToken } = req.body

  try {
    const { userId, type } = security.verify(tmpToken) && security.decode(tmpToken)

    if (type !== 'password_valid_needs_second_factor_token') {
      throw new Error('Invalid token type')
    }

    const user = await UserModel.findByPk(userId)
    if (user == null) {
      throw new Error('No such user found!')
    }

    const isValid = verifySync({ secret: user.totpSecret, token: totpToken, epochTolerance: 30 }).valid

    const plainUser = utils.queryResultToJson(user)

    if (!isValid) {
      return res.status(401).send()
    }
    challengeUtils.solveIf(challenges.twoFactorAuthUnsafeSecretStorageChallenge, () => { return user.email === 'wurstbrot@' + config.get<string>('application.domain') })

    const [basket] = await BasketModel.findOrCreate({ where: { UserId: userId } })

    const token = security.authorize(plainUser)
    // @ts-expect-error FIXME set new property for original basket
    plainUser.bid = basket.id // keep track of original basket for challenge solution check
    security.authenticatedUsers.put(token, plainUser)

    res.json({ authentication: { token, bid: basket.id, umail: user.email } })
  } catch (error) {
    res.status(401).send()
  }
}

/**
 * Check the 2FA status of the currently signed-in user.
 *
 * When 2FA is not set up, the result will include data required to start the setup.
 */
export async function status (req: Request, res: Response) {
  try {
    const user = await currentUserFromDatabase(req)

    if (user.totpSecret === '') {
      const secret = generateSecret()

      res.json({
        setup: false,
        secret,
        email: user.email,
        setupToken: security.authorize({
          secret,
          type: 'totp_setup_secret'
        })
      })
    } else {
      res.json({
        setup: true
      })
    }
  } catch (error) {
    res.status(401).send()
  }
}

/**
 * Sets Up 2FA for a User
 * Requires 3 params:
 * 1. The Users Password as a confirmation.
 * 2. A Setup token. This is returned by the status endpoint.
 *    This contains a signed TOTP secret to ensure that the secret
 *    was generated by the server and wasn't tampered with by the client
 * 3. The first TOTP Token, generated by the TOTP App. (e.g. Google Authenticator)
 */
export async function setup (req: Request, res: Response) {
  try {
    const user = await currentUserFromDatabase(req)

    const { password, setupToken, initialToken } = req.body

    if (user.password !== security.hash(password)) {
      throw new Error('Password doesnt match stored password')
    }

    if (user.totpSecret !== '') {
      throw new Error('User has 2fa already setup')
    }

    const { secret, type } = security.verify(setupToken) && security.decode(setupToken)
    if (type !== 'totp_setup_secret') {
      throw new Error('SetupToken is of wrong type')
    }
    if (!verifySync({ secret, token: initialToken, epochTolerance: 30 }).valid) {
      throw new Error('Initial token doesnt match the secret from the setupToken')
    }

    // Update db model and cached object
    user.totpSecret = secret
    await user.save()
    security.authenticatedUsers.updateFrom(req, utils.queryResultToJson(user))

    res.status(200).send()
  } catch (error) {
    res.status(401).send()
  }
}

/**
 * Disables 2fa for the current user
 */
export async function disable (req: Request, res: Response) {
  try {
    const user = await currentUserFromDatabase(req)

    const { password } = req.body

    if (user.password !== security.hash(password)) {
      throw new Error('Password doesnt match stored password')
    }

    // Update db model and cached object
    user.totpSecret = ''
    await user.save()
    security.authenticatedUsers.updateFrom(req, utils.queryResultToJson(user))

    res.status(200).send()
  } catch (error) {
    res.status(401).send()
  }
}
